extname: .md
github_repo: bolasblack/BlogPosts

url: http://plafer.info/
title: "c4605's blog"
description: ''
lang: 'zh-CN'
author_name: c4605
author_email: bolasblack@gmail.com
author_uri: https://github.com/bolasblack
