extname: .md
github_repo: bolasblack/BlogPosts

url: https://plafer.info/
article_url: "#/goto/articles/{mdUrl}"
title: "c4605's blog"
description: ""
lang: "zh"
author_name: c4605
author_email: bolasblack@gmail.com
author_uri: https://github.com/bolasblack
